apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  annotations:
    portworx.io/is-openshift: 'true'
    portworx.io/preflight-check: 'false'
  name: portworx
  namespace: openshift-operators
spec:
  revisionHistoryLimit: 10
  startPort: 17001
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                  - 'false'
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
          - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                  - 'false'
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/master
                operator: Exists
              - key: node-role.kubernetes.io/worker
                operator: Exists
          - matchExpressions:
              - key: px/enabled
                operator: NotIn
                values:
                  - 'false'
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
              - key: node-role.kubernetes.io/worker
                operator: Exists
  stork:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
  kvdb:
    internal: true
  imagePullPolicy: Always
  secretsProvider: k8s
  version: 3.1.0
  csi:
    enabled: true
    installSnapshotController: true
  image: 'portworx/oci-monitor:3.1.0'
  storage:
    devices:
      - /dev/sda
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate